POST http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNhbGliYW4iLCJpZCI6IjYzZjgyYmE1ZGNlNmFlOTUwNDVlZGJhNyIsImlhdCI6MTY3NzUxNjc4MiwiZXhwIjoxNjc3NTIwMzgyfQ.yVc-oD9YO01uuni4gFPp8AVCl3iNTdHRfwczvMqT_wc
Content-Type: application/json

{
    "title": "Prueba del error del frontend",
    "author": "Sebastian Marrera",
    "url": "example-url"
}