PUT http://localhost:3003/api/blogs/63f59661c7072f520fcc2ff2
Content-Type: application/json

{
    "title": "Blog editado",
    "author": "Sebastian Marrera",
    "url": "example-url",
    "likes": 10
}