PUT http://localhost:3003/api/blogs/63ead62f3db09327485d99ad
Content-Type: application/json

{
    "title": "Blog para borrar luego",
    "author": "Sebastian Marrera",
    "url": "example-url",
    "likes": 10
}